author: DeltaWhy
database: false
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: net.miscjunk.fancyshop.FancyShop
name: FancyShop
startup: postworld
version: '${pom.version}'
commands:
    fancyshop:
        aliases: [fs, shop]
permissions:
    fancyshop.create:
        description: Create a shop.
        default: true
    fancyshop.use:
        description: Use other people's shops.
        default: true
    fancyshop.remove:
        description: Remove someone else's shop (you can always remove your own)
        default: op
    fancyshop.open:
        description: Open chests for other people's shops.
        default: op
    fancyshop.setadmin:
        description: Create unlimited (admin) shops.
        default: op
